### ISSUE TITLE
Add Circle

### ISSUE THREAD

**Issue by 20chan** [20chan/cirno#1]
Add shape `Circle`.

- [ ] Add shape `Circle`, using center position and radius
- [ ] Implments:
  - [ ] Equals, HashCode
  - [ ] Clone
  - [ ] Check two circles are sharing center
  - [ ] Intersections
    - [ ] `Line` and `Circle`
    - [ ] `LineSegment` and `Circle`
    - [ ] `Circle` and `Circle` (maybe easiest one)

FYI: There are good articles about intersection of line and circle[1](http://mathworld.wolfram.com/Circle-LineIntersection.html) [2](https://stackoverflow.com/questions/1073336/circle-line-segment-collision-detection-algorithm)

**Comment by asmarton** [comment]
Hi! I'd like to work on this one.

**Comment by 20chan** [comment]
@brown121407 It's VERY WELCOME!!!

**Comment by asmarton** [comment]
@20chan if two circles are identical (radius of A is equal to radius of B and the center coincides) how do you want to handle intersection? Are the two circles considered to intersect or not? If yes, mathematically they have infinitely many intersection points. That's impossible to translate into a `out Vector[] intersects`. If two identical circles are considered to intersect, should the `intersects` array be empty?

**Comment by 20chan** [comment]
@brown121407 It should return false.
